replicaCount: 1

image:
  repository: operatr/kpow
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}
envFromConfigMap: null
envFromSecret: null
volumeMounts: []
# - name: rbac-config
#   mountPath: /path/to/rbac-config.yaml
#   subPath: rbac-config.yaml
volumes: []
# - name: rbac-config
#   configMap:
#     name: "my-kpow-config"

serviceAccount:
  create: true
  annotations: {}
  name: kpow

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
  ingressClassName: ""

# We recommend running kPow w/ Guaranteed QOS class and 1 CPU / 4G Memory.
# Small resource sets (e.g. 1 cluster, 1 schema registry, 1 connect cluster) can likely run with 1 CPU / 2G Memory.
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

nodeSelector: {}

tolerations: []

affinity: {}
