replicaCount: 1

image:
  repository: factorhouse/kpow
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}
envFromConfigMap: null
envFromSecret: null
volumeMounts: []
# - name: rbac-config
#   mountPath: /path/to/rbac-config.yaml
#   subPath: rbac-config.yaml
volumes: []
# - name: rbac-config
#   configMap:
#     name: "my-kpow-config"

serviceAccount:
  create: true
  annotations: {}
  name: kpow

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
  ingressClassName: ""

# We recommend running Kpow w/ Guaranteed QOS
# The default resource limit/requests are suitable for a multi-cluster installation (up to 12 Kafka Clusters + Connect + Schema).
# For a smaller installation (up to 6 clusters) you can modify to 1CPU, 4GB heap, monitor performance afterwards and adjust as necessary.
# For a single cluster you can modify to 0.5CPU, 2GB heap, monitor performance afterwards and adjust as necessary.
# These resources also depend on the size of the clusters (number of brokers/topics/groups in particular).
# The default settings are suitable for even the largest single cluster installation. For tuning assistance contact support@factorhouse.io
resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 2
    memory: 8Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}