{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kpow.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kpow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- else -}}
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
            {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
